name: Update AoC Badges

on:
  schedule:
    - cron: '0 */1 * 12 *'
    - cron: '0 0 * 1-11 *'
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update 2015 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2015'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2015-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2016 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2016'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2016-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2017 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2017'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2017-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2018 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2018'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2018-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2019 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2019'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2019-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2020 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2020'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2020-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2021 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2021'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2021-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2022 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2022'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2023 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2023'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2023-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Update 2024 Badge
        uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: ${{ secrets.AOC_USER_ID }}
          session: ${{ secrets.AOC_SESSION }}
          year: '2024'
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2024-)[0-9]+(?=%2F50-FBC901)'
          dayRegex: 'this-will-not-match-anything'
          daysCompletedRegex: 'this-will-not-match-anything'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update AoC badges [skip ci]'
          file_pattern: 'README.md'
